version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    # Always increase the version requirement
    # to match the new version.
    versioning-strategy: increase
    # Only do security updates
    open-pull-requests-limit: 0
